version: '2.1'
services:
  nifi-112:
    image: chaffelson/nifi:1.1.2
    container_name: nifi-112
    hostname: nifi-112
    ports:
      - "10112:8080"
  nifi-120:
    image: apache/nifi:1.2.0
    container_name: nifi-120
    hostname: nifi-120
    ports:
      - "10120:8080"
  nifi-180:
    image: apache/nifi:1.8.0
    container_name: nifi-180
    hostname: nifi-180
    ports:
      - "10180:8080"
  nifi:
    image: apache/nifi:1.10.0
    container_name: nifi
    hostname: nifi
    ports:
      - "8080:8080"
  registry-010:
    image: apache/nifi-registry:0.1.0
    container_name: registry-010
    hostname: registry-010
    ports:
      - "18010:18010"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18010
  registry:
    image: apache/nifi-registry:0.5.0
    container_name: registry
    hostname: registry
    ports:
      - "18080:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
