services:
  nifi-192:
    image: apache/nifi:1.9.2
    container_name: nifi-192
    hostname: nifi-192
    ports:
      - "10192:8080"
  nifi-127:
    image: apache/nifi:1.27.0
    container_name: nifi-127
    hostname: nifi-127
    ports:
      - "10127:10127"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nobel
      - SINGLE_USER_CREDENTIALS_PASSWORD=supersecret1!
      - NIFI_WEB_HTTPS_PORT=10127
  nifi:
    image: apache/nifi:2.2.0
    container_name: nifi
    hostname: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nobel
      - SINGLE_USER_CREDENTIALS_PASSWORD=supersecret1!
  registry-030:
    image: apache/nifi-registry:0.3.0
    container_name: registry-030
    hostname: registry-030
    ports:
      - "18030:18030"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18030
  registry-127:
    image: apache/nifi-registry:1.27.0
    container_name: registry-127
    hostname: registry-127
    ports:
      - "18127:18127"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18127
  registry:
    image: apache/nifi-registry:2.2.0
    container_name: registry
    hostname: registry
    ports:
      - "18080:18080"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
