version: '2.1'
services:
  nifi-secure:
    image: apache/nifi:1.9.1
    container_name: nifi-secure
    ports:
      - "8443:8443"
    volumes:
      - ../../../nipyapi/demo/keys:/opt/certs:ro
    environment:
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/localhost-ks.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=localhostKeystorePassword
      - TRUSTSTORE_PATH=/opt/certs/localhost-ts.jks
      - TRUSTSTORE_PASSWORD=localhostTruststorePassword
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=user1, OU=nifi
  registry-secure:
    image: apache/nifi-registry:0.3.0
    container_name: registry-secure
    ports:
      - "18443:18443"
    volumes:
      - ../../../nipyapi/demo/keys:/opt/certs:ro
    environment:
      - NIFI_REGISTRY_WEB_HTTPS_PORT=18443
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/localhost-ks.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=localhostKeystorePassword
      - TRUSTSTORE_PATH=/opt/certs/localhost-ts.jks
      - TRUSTSTORE_PASSWORD=localhostTruststorePassword
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=user1, OU=nifi
