version: '2.1'
services:
  secure-nifi:
    image: apache/nifi:1.9.1
    container_name: secure-nifi
    hostname: secure-nifi
    ports:
      - "8443:8443"
    volumes:
      - ../../../nipyapi/demo/keys:/opt/certs:ro  # Min docker version tested 18, does not work on old docker
    environment:
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/localhost-ks.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=localhostKeystorePassword
      - TRUSTSTORE_PATH=/opt/certs/localhost-ts.jks
      - TRUSTSTORE_PASSWORD=localhostTruststorePassword
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=user1, OU=nifi
  secure-registry:
    image: apache/nifi-registry:0.3.0
    container_name: secure-registry
    hostname: secure-registry
    ports:
      - "18443:18443"
    volumes:
      - ../../../nipyapi/demo/keys:/opt/certs:ro
    environment:
      - NIFI_REGISTRY_WEB_HTTPS_PORT=18443
      - AUTH=tls
      - KEYSTORE_PATH=/opt/certs/localhost-ks.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=localhostKeystorePassword
      - TRUSTSTORE_PATH=/opt/certs/localhost-ts.jks
      - TRUSTSTORE_PASSWORD=localhostTruststorePassword
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=CN=user1, OU=nifi
