version: '2'
# the latest tag is not pulling the latest image on Travis, so setting explicit
services:
  nifi-150:
    image: apache/nifi:1.7.1
    container_name: nifi
    ports:
      - "8080:8080"
  registry-020:
    image: apache/nifi-registry:0.2.0
    container_name: registry
    ports:
      - "18080:18080"
