services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nobel
      - SINGLE_USER_CREDENTIALS_PASSWORD=supersecret1!
  registry:
    image: apache/nifi-registry:latest
    container_name: registry
    hostname: registry
    ports:
      - "18080:18080"
